<a href="https://colab.research.google.com/github/falwa-alkhalifah/Mining-project/blob/main/Dataset_Description.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset Info:

Number of objects: 1001

Number of attributes: 14

Class label: Diabetic (Y), Non-Diabetic(N), or Predict-Diabetic(P).

------------------------------------------------------------------------------
Types of Attributes:

1) Id: Nominal

2) Gender: Nominal (Binary)

3) Urea: Numeric interval float
4) Cr: Numeric interval float

5) HbA1c: Numeric interval float

6) Chol: Numeric interval float

7) BMI: Numeric ratio float

8) TG: Numeric interval float

9) HDL: Numeric interval float

10) LDL: Numeric interval float

11) VLDL: Numeric interval float

12) Age: Numeric ratio integer

13) Class: Nominal (Binary)

------------------------------------------------------------------------------

Columns Description:
Id: Unique identifier for each data entry.
Gender: Male Or Female.
LDL: LDL (Low-Density Lipoprotein) shows the level of "bad cholesterol" in the blood. It is measured in mg/dL and helps check the risk of heart problems in people with diabetes.
Urea: Urea shows the level of waste in the blood from breaking down protein. It is measured in mg/dL and checks kidney health in diabetes.
CR: Creatinine ratio in a diabetic dataset checks kidney health by measuring waste levels in the blood. It helps detect early signs of kidney damage common in diabetes.
HbA1c: measures the average blood sugar level over the past 2-3 months and is used to monitor long-term diabetes control.
TG: (Triglycerides) measures blood fat levels and helps assess heart disease risk in diabetics.
BMI: Body mass index (weight in kg / height in m^2).
HDL: (High-Density Lipoprotein) is "good cholesterol" that helps protect against heart disease.
VLDL: (Very Low-Density Lipoprotein) is a type of bad cholesterol that can increase heart disease risk by raising fat levels in the blood.
Chol: (Total Cholesterol) measures the overall level of cholesterol in the blood, including both good and bad types, and helps assess heart disease risk.
Age: Age in years.
Class: the patient's diabetes disease class may be Diabetic, Non-Diabetic, or Predict-Diabetic.

------------------------------------------------------------------------------
goal:The goal of this project is to apply data mining techniques to analyze and extract meaningful insights from the diabetes dataset collected from medical institutions in Iraq. This involves using classification and clustering methods to understand the relationships between medical attributes such as blood sugar levels, BMI, cholesterol levels, and HbA1C, and their impact on categorizing patients as Diabetic, Non-Diabetic, or Predict-Diabetic

The source of the dataset: https://www.kaggle.com/datasets/aravindpcoder/diabetes-dataset

In [10]:
import pandas as pd

url = 'https://raw.githubusercontent.com/falwa-alkhalifah/Mining-project/refs/heads/main/Dataset/Dataset%20of%20Diabetes%20.csv'

df  = pd.read_csv(url)

print(df .head())

    ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
1  735      34221      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6
2  420      47975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
3  680      87656      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5
4  504      34223      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4

    BMI CLASS
0  24.0     N
1  23.0     N
2  24.0     N
3  24.0     N
4  21.0     N

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB

In [12]:
df.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [13]:
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [14]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Column names:", df.columns)

Number of rows: 1000
Number of columns: 14
Column names: Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [22]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import LabelEncoder


df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
df['CLASS'] = LabelEncoder().fit_transform(df['CLASS'])

X = df.drop(columns=["CLASS"])
y = df["CLASS"]
selector = SelectKBest(score_func=f_classif, k=5)
X_new = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]
print("Selected Features:", selected_features.tolist())

Selected Features: ['AGE', 'HbA1c', 'Chol', 'TG', 'BMI']

In [21]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)

selected_features = X.columns[selector.get_support()]
print("Selected Features after Variance Threshold:", selected_features.tolist())

Selected Features after Variance Threshold: ['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']